// Generates components/core/logo-data.js — the KLF lockup inlined as a data URI.
//
// Logo renders an <img> at a path relative to the page ('assets/klf-logo.png').
// That only resolves when the host app happens to serve the artwork at that
// path, which is false in a preview card, in a rendered design, and in any app
// served from a subdirectory — the mark just 404s, silently. Inlining makes the
// default case always correct; passing `basePath` still switches back to a real
// file for apps that serve their own copy.
//
//   node build-logo.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = 'assets/klf-logo.png';

const b64 = readFileSync(join(ROOT, SRC)).toString('base64');
const out = `// Generated by build-logo.mjs — do not edit. Source: ${SRC}
// The KLF Group Inc lockup, inlined so it renders with no asset hosting.

export const LOGO_DATA = "data:image/png;base64,${b64}";
`;

writeFileSync(join(ROOT, 'components/core/logo-data.js'), out);
console.log(`logo-data.js — ${(out.length / 1024).toFixed(1)} KB from ${SRC}`);
