// Generates components/core/icon-data.js — the Lucide glyphs the design system
// ships with, inlined as data URIs.
//
// Icon paints its glyph as a CSS mask so it can be tinted with currentColor. It
// used to point that mask at unpkg.com, which meant every icon in every design
// depended on a network fetch at render time and vanished silently wherever
// outside requests are blocked. These are baked in instead; anything not in the
// list still falls back to the CDN.
//
//   node build-icons.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'node_modules/lucide-static/icons');

// The freight/dispatch vocabulary: everything the components reference by
// default, plus the set a dispatch or driver UI reaches for. Add a name here and
// re-run to ship it.
const ICONS = [
  // referenced directly by components
  'truck', 'check', 'chevron-down', 'x', 'info', 'circle-check', 'check-circle',
  'triangle-alert', 'octagon-alert',
  // navigation + chrome
  'chevron-up', 'chevron-left', 'chevron-right', 'menu', 'search', 'filter',
  'settings', 'bell', 'log-out', 'external-link', 'more-horizontal', 'link',
  // freight + fleet
  'map-pin', 'map', 'navigation', 'route', 'package', 'boxes', 'container',
  'warehouse', 'building-2', 'fuel', 'gauge', 'weight', 'snowflake',
  // documents + compliance
  'clipboard-check', 'clipboard-list', 'file-text', 'file-check', 'receipt',
  'shield-check', 'lock',
  // money
  'dollar-sign', 'credit-card', 'trending-up', 'trending-down',
  // people + contact
  'users', 'user', 'user-plus', 'mail', 'phone', 'message-circle',
  // time
  'calendar', 'clock',
  // actions
  'plus', 'minus', 'pencil', 'trash-2', 'copy', 'download', 'upload',
  'refresh-cw', 'eye', 'camera', 'image', 'play', 'pause',
  // status + misc
  'circle-alert', 'circle-help', 'star', 'thumbs-up', 'loader', 'arrow-right',
  'arrow-left', 'arrow-up', 'arrow-down',
];

const entries = [];
const missing = [];
for (const name of ICONS) {
  const file = join(SRC, `${name}.svg`);
  if (!existsSync(file)) { missing.push(name); continue; }
  // Collapse whitespace so the data URI stays compact, then percent-encode the
  // characters that are not safe inside a url() token.
  const svg = readFileSync(file, 'utf8').replace(/\s+/g, ' ').trim();
  const uri = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(uri)},`);
}

const out = `// Generated by build-icons.mjs — do not edit.
// ${entries.length} Lucide glyphs, inlined so Icon never needs the network.

export const ICON_DATA = {
${entries.join('\n')}
};
`;

writeFileSync(join(ROOT, 'components/core/icon-data.js'), out);
console.log(`icon-data.js — ${entries.length} icons, ${(out.length / 1024).toFixed(1)} KB`);
if (missing.length) console.warn(`! not in lucide-static: ${missing.join(', ')}`);
