// Generates dist/global.css — the rule-bearing stylesheet the components rely on
// but cannot express as inline styles: the resets and element defaults from
// tokens/base.css, and the @keyframes from tokens/motion.css that Dialog and
// Toast animate with.
//
// The token *variables* ship separately as tokens/*.css; this file is what the
// design-system bundle points `cssEntry` at, so those rules reach every design
// rendered from the bundle.
//
//   node build-css.mjs
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SOURCES = ['tokens/base.css', 'tokens/motion.css'];

const out = SOURCES.map(
  (f) => `/* --- ${f} --- */\n${readFileSync(join(ROOT, f), 'utf8').trim()}\n`,
).join('\n');

mkdirSync(join(ROOT, 'dist'), { recursive: true });
writeFileSync(
  join(ROOT, 'dist/global.css'),
  `/* Generated by build-css.mjs — do not edit. Sources: ${SOURCES.join(', ')} */\n\n${out}`,
);
console.log(`dist/global.css — ${out.length} bytes from ${SOURCES.length} sources`);
